version: '3.8'
services:
  authorization-db:
    image: latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pox
    networks:
    - public
    ports:
    - mode: host
      published: 3306
      target: 3306
    volumes:
    - mysql_data:/var/lib/mysql
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints: [node.hostname == ds-worker1]
